# Generated by Django 5.0.3 on 2024-03-21 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='checkliste',
            field=models.ForeignKey(default='Checkliste A', on_delete=django.db.models.deletion.CASCADE, to='haccp.checkliste', to_field='checkliste_name'),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='mangel',
            field=models.ForeignKey(default='keiner', on_delete=django.db.models.deletion.CASCADE, to='haccp.mangelart', to_field='mangelart_name'),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='objektort',
            field=models.ForeignKey(default='Boden', on_delete=django.db.models.deletion.CASCADE, to='haccp.objektort', to_field='objektort_name'),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='ok',
            field=models.ForeignKey(default='in Ordnung', on_delete=django.db.models.deletion.CASCADE, to='haccp.oknok', to_field='oknok_name'),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='pruefpunkt',
            field=models.ForeignKey(default='sauber', on_delete=django.db.models.deletion.CASCADE, to='haccp.audit', to_field='audit_name'),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='von',
            field=models.ForeignKey(default='Gerhard', on_delete=django.db.models.deletion.CASCADE, to='haccp.benutzer', to_field='benutzer_name'),
        ),
        migrations.AlterField(
            model_name='benutzer',
            name='benutzer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='checkliste',
            name='checkliste_name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='mangelart',
            name='mangelart_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='objektort',
            name='objektort_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='oknok',
            name='oknok_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
