# Generated by Django 5.0.3 on 2024-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='text',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='checkliste',
            field=models.CharField(default='checkliste', max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='frist',
            field=models.CharField(default='frist', max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='mangel',
            field=models.CharField(default='mangel', max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='objekt',
            field=models.CharField(default='objekt', max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='ok',
            field=models.CharField(default='ok', max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='pruefpunkt',
            field=models.CharField(default='pruefpunkt', max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='von',
            field=models.CharField(default='von', max_length=100),
        ),
    ]
