# Generated by Django 5.0.3 on 2024-03-17 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0002_remove_todoitem_due_date_remove_todoitem_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='behoben',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
