# Generated by Django 5.0.3 on 2024-03-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0004_alter_todoitem_checkliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='pruefpunkt',
            field=models.CharField(choices=[('1', 'sauber'), ('2', 'leicht zu reinigen'), ('3', 'nicht schadhaft'), ('4', 'keine Schimmelbildung.'), ('5', 'Insektengitter'), ('6', 'ausreichend'), ('7', 'leicht zu warten und zu reinigen'), ('8', 'funktionstüchtig'), ('9', 'Temperaturüberwachung'), ('10', 'Linie der maximalen Befüllung'), ('11', 'ordnungsgemäß'), ('12', 'Wände glatt bis zu angemessener Höhe')], default='1', max_length=3),
        ),
    ]
