# Generated by Django 5.0.3 on 2024-03-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0005_alter_todoitem_pruefpunkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='objekt_ort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eintrag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='objekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.objekt_ort'),
        ),
    ]
