# Generated by Django 5.0.3 on 2024-03-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0006_objekt_ort_alter_todoitem_objekt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='objekt',
            new_name='objektort',
        ),
    ]
