# Generated by Django 5.0.3 on 2024-03-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0007_rename_objekt_todoitem_objektort'),
    ]

    operations = [
        migrations.CreateModel(
            name='mangel_art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pruef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruefung', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='ok',
            field=models.CharField(choices=[('1', 'in Ordnung'), ('2', 'nicht in Ordnung')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='mangel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.mangel_art'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='pruefpunkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.pruef'),
        ),
    ]
