# Generated by Django 5.0.3 on 2024-03-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0008_mangel_art_pruef_alter_todoitem_ok_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mangel_art',
            new_name='Audit',
        ),
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='AuditAnlass',
        ),
        migrations.RenameModel(
            old_name='pruef',
            new_name='MangelArt',
        ),
        migrations.RenameModel(
            old_name='objekt_ort',
            new_name='ObjektOrt',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='mangel',
            new_name='pruefung',
        ),
        migrations.RenameField(
            model_name='mangelart',
            old_name='pruefung',
            new_name='mangel',
        ),
    ]
