# Generated by Django 5.0.3 on 2024-03-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0009_rename_mangel_art_audit_rename_todoitem_auditanlass_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditAnlass',
            new_name='Audit_Ereignis',
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='mangel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.mangelart'),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='pruefpunkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.audit'),
        ),
    ]
