# Generated by Django 5.0.3 on 2024-03-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0010_rename_auditanlass_audit_ereignis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benutzer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Checkliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='frist',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='von',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.benutzer'),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='checkliste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.checkliste'),
        ),
    ]
