# Generated by Django 5.0.3 on 2024-03-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0013_alter_audit_ereignis_mangel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_ereignis',
            name='frist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='mangel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haccp.mangelart'),
        ),
    ]
