# Generated by Django 5.0.3 on 2024-03-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0014_alter_audit_ereignis_frist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='pruefung',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='benutzer',
            old_name='benutzer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='checkliste',
            old_name='liste',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mangelart',
            old_name='mangel',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='objektort',
            old_name='eintrag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='frist',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='mangel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.mangelart'),
        ),
    ]
