# Generated by Django 5.0.3 on 2024-03-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0015_rename_pruefung_audit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='oknok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='audit_ereignis',
            name='ok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.oknok'),
        ),
    ]
