# Generated by Django 5.0.3 on 2024-03-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0017_alter_audit_ereignis_ok_alter_oknok_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_ereignis',
            name='ok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccp.oknok'),
        ),
        migrations.AlterField(
            model_name='oknok',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
